### ISSUE TITLE
Maven version of the plugin

### ISSUE THREAD

**Issue by athkalia** [xfumihiro/DataInspector#3]
Hello,

this looks lovely! Is there any chance I can make this work with maven instead of gradle? 

Cheers

**Comment by xfumihiro** [comment]
Sorry, it's a gradle plugin afterall.

**Comment by xfumihiro** [comment]
I won't have the time to do it.
So PRs or side projects are welcome!

**Comment by athkalia** [comment]
thanks for the reply. You can close this, I would have to first have a look at gradle before attempting to migrate anything ! And if I do have a look at gradle i'll end up using it as maven starts getting deprecated for android dev : )

**Comment by xfumihiro** [comment]
No prob. :beer:
