### ISSUE TITLE
顶部按钮不显示，leakcanary 显示leak

### ISSUE THREAD

**Issue by tinybright** [xfumihiro/DataInspector#6]

**Comment by tinybright** [comment]
m3 api19
![screenshot_2016-02-15-16-23-10_com github xfumihi](https://cloud.githubusercontent.com/assets/8720949/13043060/9b3a1248-d400-11e5-805e-af00131655e0.png)
![screenshot_2016-02-15-16-23-19_com protontek vcar](https://cloud.githubusercontent.com/assets/8720949/13043062/9c22e2d4-d400-11e5-8a8e-74dcd9e9c914.png)

**Comment by xfumihiro** [comment]
Can you share the build.gradle?

**Comment by tinybright** [comment]
app build.gradle

```
apply plugin: 'com.android.application'
apply plugin: 'im.fir.plugin.gradle'
apply plugin: 'packer'
apply plugin: 'view-inspector'
//apply plugin: 'com.jakewharton.hugo'
repositories {
    mavenCentral()
    jcenter()
    flatDir{
        dirs 'aar'
    }
}
viewInspector {
    excludePackages = ['android.widget.Space', 'com.squareup.leakcanary.internal' ,'com.github.moduth.blockcanary.ui']
}
```

root build.gradle

```
buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://repos.zeroturnaround.com/nexus/content/repositories/zt-public-releases'
        }
        maven {
            url "http://maven.bughd.com/public"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-beta4'
        classpath 'com.mcxiaoke.gradle:packer:1.0.+'
        classpath 'im.fir:gradle-fir-publisher:1.0.0'
//        classpath 'com.github.xfumihiro.view-inspector:view-inspector-plugin:0.2.0'
//        classpath 'com.github.xfumihiro.data-inspector:data-inspector-plugin:0.1.1'
    }
}
```

**Comment by xfumihiro** [comment]
It seems working with gradle-android-plugin:2.0.0-beta4.
Can you make sure other plugins are working fine with DataInspector too?

**Comment by tinybright** [comment]
I think it has some thing to do with how you implement the top menu.

**Comment by xfumihiro** [comment]
You mean the DataInspectorToolbar class?

**Comment by tinybright** [comment]
I just can't see the menu on statusbar
![22](https://cloud.githubusercontent.com/assets/8720949/13099239/50698548-d56b-11e5-91d6-74854b8e06a0.png)

**Comment by xfumihiro** [comment]
Is the sample app working on your device?

**Comment by tinybright** [comment]
Picture 1 is sample app.

**Comment by xfumihiro** [comment]
Seems like a device related issue.
The plugin UI is implemented as adding overlay views on the top.

**Comment by xfumihiro** [comment]
Can you confirm if system overlay views work on your device?
(Try [Telecine](https://github.com/JakeWharton/Telecine))

**Comment by tinybright** [comment]
My api level is 19 . Api level of Telecine is 21.

**Comment by xfumihiro** [comment]
Oops! Can You try add some overlay view and see if it works?
Also I'm curious about what model the device is, are you using stock ROM or custom ones(like cyanogenmod), any Exposed modules used?

**Comment by tinybright** [comment]
I can use overlayview in Activity.But I haven't found sample of 
overlayview in statusbar.

**Comment by xfumihiro** [comment]
Are you using Exposed module to re-arrange the status bar?
Normally the "Time" should be on the right side.

**Comment by tinybright** [comment]
No. It's MiUi.

**Comment by xfumihiro** [comment]
I think it's the custom ROM(MIUI) preventing this plugin from adding overlay views on the status bar.
In order to make this plugin useful for all cases, toolbar overlay views must be on the status bar.
I'm closing the issue as it's outside the project's scope.

**Comment by tinybright** [comment]
MIUI is main OS of Android Mobile in China.

**Comment by xfumihiro** [comment]
Still it's a custom ROM compare to AOSP ones, right?
If it's true that MIUI prevents user's app to draw overlay views on the status bar then there's nothing we can do.

**Comment by tinybright** [comment]
I sloved it.It requests <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" /> and MIUI disables it normally.

**Comment by xfumihiro** [comment]
:+1:
